### ISSUE TITLE
tensorf problem

### ISSUE THREAD

**Issue by seesee412** [KAIR-BAIR/nerfacc#230]
Hi Ruilong,
Thanks so much for your project, but I face a problem trying tensorf in the benchmark.
Here is the error:
```
Traceback (most recent call last):
  File "train.py", line 577, in <module>
    reconstruction(args)
  File "train.py", line 460, in reconstruction
    new_aabb = tensorf.updateAlphaMask(tuple(reso_mask))
  File "/opt/conda/envs/nerfacc/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "tensorf/models/tensorBase.py", line 466, in updateAlphaMask
    xyz_min = valid_xyz.amin(0)
IndexError: amin(): Expected reduction dim 0 to have non-zero size.
```
it seems "valid_xyz" become a none tensor after mask, so I reduce the "--alpha_mask_thre" to a lower value. Now there is no error, but still not converge after 15000 iter. Do you have any suggestions about this issue?

**Comment by liruilong940607** [comment]
Hi which command is you running? I can take a look at tmr as it's pretty late in my time zone.

**Comment by liruilong940607** [comment]
And what's your nerfacc version btw? 
```
python -c "import nerfacc; print(nerfacc.__version__)"
```
