### ISSUE TITLE
time.sleep

### ISSUE THREAD

**Issue by LHXhh** [KAIR-BAIR/nerfacc#79]
Could you please help me?

(nerfacc) lhx@lhx:~/NeRF/nerfacc$ /home/lhx/miniconda3/envs/nerfacc/bin/python /home/lhx/NeRF/nerfacc/examples/train_mlp_nerf.py
^CTraceback (most recent call last):
  File "/home/lhx/NeRF/nerfacc/examples/train_mlp_nerf.py", line 173, in <module>
    occupancy_grid.every_n_step(
  File "/home/lhx/miniconda3/envs/nerfacc/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/lhx/NeRF/nerfacc/nerfacc/grid.py", line 275, in every_n_step
    self._update(
  File "/home/lhx/miniconda3/envs/nerfacc/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/lhx/NeRF/nerfacc/nerfacc/grid.py", line 228, in _update
    x = contract_inv(
  File "/home/lhx/miniconda3/envs/nerfacc/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/lhx/NeRF/nerfacc/nerfacc/contraction.py", line 102, in contract_inv
    ctype = type.to_cpp_version()
  File "/home/lhx/NeRF/nerfacc/nerfacc/contraction.py", line 63, in to_cpp_version
    return _C.ContractionTypeGetter(self.value)
  File "/home/lhx/NeRF/nerfacc/nerfacc/cuda/__init__.py", line 11, in call_cuda
    from ._backend import _C
  File "/home/lhx/NeRF/nerfacc/nerfacc/cuda/_backend.py", line 38, in <module>
    _C = load_extention(name)
  File "/home/lhx/NeRF/nerfacc/nerfacc/cuda/_backend.py", line 25, in load_extention
    return load(
  File "/home/lhx/miniconda3/envs/nerfacc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "/home/lhx/miniconda3/envs/nerfacc/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1439, in _jit_compile
    baton.wait()
  File "/home/lhx/miniconda3/envs/nerfacc/lib/python3.9/site-packages/torch/utils/file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt

**Comment by liruilong940607** [comment]
Please see https://github.com/KAIR-BAIR/nerfacc/issues/70#issuecomment-1279782194

**Comment by LHXhh** [comment]
Thank you very much, I have solved it!
